{
  "hash": "37a7d8b3ed22dbf80b79616ef5a49a1d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Talyah Pierce\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n## Setup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a sample, not a count. That means every number comes with a margin of error — a statement about how wrong it might be. Most people ignore it. In this assignment, you won't.\n\nIn this analysis, I am looking at the estimated number of individuals with bachelors degrees in all 14 counties across Massachusetts. Here, I will look at how counties of varying population sizes produce more or less reliable estimates of population characteristics, specifically the number of individuals with bachelors degrees. This analysis will shed light on how the surveys that rely on random samples to generalize population characteristics, like the American Community Survey, may inaccurately represent areas with smaller populations.\n\n---\n\n\n## Choosing what to measure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"MA\"       \nmy_variable <- \"B15003_022\"    \n```\n:::\n\n\n\n## Pulling the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                             variable   estimate   moe\n  <chr> <chr>                            <chr>         <dbl> <dbl>\n1 25001 Barnstable County, Massachusetts B15003_022    46953  1690\n2 25003 Berkshire County, Massachusetts  B15003_022    19480  1015\n3 25005 Bristol County, Massachusetts    B15003_022    79826  2184\n4 25007 Dukes County, Massachusetts      B15003_022     4170   732\n5 25009 Essex County, Massachusetts      B15003_022   140926  2477\n6 25011 Franklin County, Massachusetts   B15003_022    11576   629\n```\n\n\n:::\n:::\n\n\n\nAfter running the line of code above, the data returned back 14 rows, indicating 14 counties in Massachusetts. This matches the number of counties listed online.\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000 than for an estimate of 200,000. To compare across places, we need it as a percentage.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                             estimate   moe moe_pct\n   <chr>                               <dbl> <dbl>   <dbl>\n 1 Dukes County, Massachusetts          4170   732   17.6 \n 2 Nantucket County, Massachusetts      3878   456   11.8 \n 3 Franklin County, Massachusetts      11576   629    5.43\n 4 Berkshire County, Massachusetts     19480  1015    5.21\n 5 Hampshire County, Massachusetts     24534   987    4.02\n 6 Hampden County, Massachusetts       54356  2058    3.79\n 7 Barnstable County, Massachusetts    46953  1690    3.60\n 8 Bristol County, Massachusetts       79826  2184    2.74\n 9 Plymouth County, Massachusetts      96359  2159    2.24\n10 Worcester County, Massachusetts    135457  2830    2.09\n```\n\n\n:::\n:::\n\n\n\nThe area with the largest margin of error relative to its estimate is Dukes County, with a margin of error percent approximately 17.6%. Because Dukes County has a smaller estimate and higher margin of error, this makes the ACS estimate less reliable.\n\n---\n\n## Sorting counties into reliability categories\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    10\n2 Low confidence      2\n3 Moderate            2\n```\n\n\n:::\n:::\n\n\n\n\nMost of the counties fall into the high confidence level category, with 10 counties in Massachusetts having a margin of error percent below 5%. Only 2 counties, Berkshire and Franklin, have a moderate confidence level between 5% and 10%. Additionally, only 2 counties, Dukes and Nantucket, have a low confidence level with a margin of error percent above 10%.\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(bachelors = my_variable,\n                pop = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                             bachelorsE bachelorsM   popE  popM\n  <chr> <chr>                                 <dbl>      <dbl>  <dbl> <dbl>\n1 25001 Barnstable County, Massachusetts      46953       1690 230073    NA\n2 25003 Berkshire County, Massachusetts       19480       1015 128047    NA\n3 25005 Bristol County, Massachusetts         79826       2184 578436    NA\n4 25007 Dukes County, Massachusetts            4170        732  20751    NA\n5 25009 Essex County, Massachusetts          140926       2477 807258    NA\n6 25011 Franklin County, Massachusetts        11576        629  70922    NA\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = bachelorsM / bachelorsE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\n\nNow compare the average population of counties in each reliability category.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         10        675838.\n2 Low confidence           1         20751 \n3 Moderate                 3         71089.\n```\n\n\n:::\n:::\n\n\n\n\n\nThe average population of high-confidence counties in Massachusetts is 675,837. The average population of low-confidence counties in Massachusetts is 20,751; however, it is worth nothing that only one county is considered in this average. This suggests that counties with higher populations have lower margins of error, producing more reliable estimates. At the county-level, due to the larger size of most counties, this is not a glaring issue in many cases. However, when working with more granular geographies (i.e., tract-level, block group-level), this effect can produce misleading estimates.\n\n---\n\n## What this means for policy\n\nBased on the analysis, the two counties we know the least about are Dukes County and Nantucket County. Interestingly enough, both counties are small island counties with active county governments, home to Nantucket and Martha’s Vineyard.\n\nThe American Community Survey (ACS) works by targeting 3.5 million addresses annually as opposed to collecting data from all households in decade intervals like the Census. Because of this, the ACS relies on these samples to produce representative estimates at each geographic level, excluding block groups. The ACS has two survey versions: a one-year survey, which provides estimates for areas with at least 65,000 people, and a five-year survey, which provides estimates of all population-level areas. Because the ACS relies on a random sample of addresses to accurately estimate data points, smaller geographic areas receive less representation, making them more likely to have less representative estimates.\n\nIf a state agency were to view data across differently populated areas the same, this would result in less-populated, likely rural areas from receiving fair representation in receiving state resources. For example, if an agency were to rely on ACS estimates to fairly allocate housing funds to Scranton, with a population of around 75,000 people, vs. Wellsboro, with a population of 3,472 people, an area like Wellsboro would like receive more variable/inconsistent funding compared to an area like Scranton with a larger population.\n\n---\n\n## Changing the geographic scale\n   \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the same code but at the tract-level for Barnstable County #\n\ncounty_wide_tract <- get_acs(\n  geography = \"tract\",\n  variables = c(bachelors = my_variable,\n                pop = \"B01003_001\"),\n  state = my_state,\n  county = \"Barnstable\",\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\n# compute the margin of error percent for bachelors degrees in Barnstable #\n\nbarnstable_moe <- county_wide_tract %>%\n  mutate(moe_pct = bachelorsM / bachelorsE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 20  ~ \"High confidence\",\n    moe_pct < 30 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(barnstable_moe, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence     7\n2 Low confidence     15\n3 Moderate           35\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(barnstable_moe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  GEOID       NAME         bachelorsE bachelorsM  popE  popM moe_pct reliability\n  <chr>       <chr>             <dbl>      <dbl> <dbl> <dbl>   <dbl> <chr>      \n1 25001010100 Census Trac…        965        227  3681    23    23.5 Moderate   \n2 25001010206 Census Trac…        790        184  4371   288    23.3 Moderate   \n3 25001010208 Census Trac…        228        111  1675   287    48.7 Low confid…\n4 25001010304 Census Trac…        629        172  2745   314    27.3 Moderate   \n5 25001010306 Census Trac…        616        185  3027   316    30.0 Low confid…\n6 25001010400 Census Trac…        815        219  3335   419    26.9 Moderate   \n```\n\n\n:::\n\n```{.r .cell-code}\n# compare different levels or reliability in Barnstable #\n\nbarnstable_moe %>%\n  group_by(reliability) %>%\n  summarize(\n    n_tracts = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_tracts avg_population\n  <chr>              <int>          <dbl>\n1 High confidence        7          4326.\n2 Low confidence        15          3731.\n3 Moderate              35          4109.\n```\n\n\n:::\n:::\n\n\n\n\nIn the code above, I chose to calculate the estimated count of individuals in Barnstable, MA that have a bachelors degree at the tract-level. To calculate the confidence levels, I adjusted the threshold for what is considered high confidence to be slightly more flexible, since tracts are a smaller geographic area than counties and inherently require a bit more flexibility.Thus, tracts with high confidence level have a margin of error percent less than 20%, tracts with a moderate confidence level have a margin of error percent between 20% and 30%, and tracts with a low confidence level have a margin of error percent greater then 30%. After grouping tracts by confidence levels and calculating the average population in each, it is clear that the pattern from the previous exercise holds. Tracts with higher confidence levels have an average population of 4,326 per tract, whereas areas with low confidence levels have an average population of 3,730.\n\nThis supplemental analysis provides evidence that discrepancies in population even at a smaller scale can yield even bigger disparities in estimates. While at the county-level a 100 or 1,000 person difference in population may not yield vastly different confidence levels, at the tract-level, this can result in glaring disparities in confidence level estimates.\n\n---\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}